services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-service
    ports:
      - 9000:9000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
volumes:
  mongo: {}